plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: bundles/@yarnpkg/plugin-engines.js
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
